---
- name: configure mayan db server
  hosts: mayandbserver
  become: true
  roles:
    - role: postgres
      postgresql_version: 10
  tasks:
    - import_tasks: tasks/postgres.yml
    - import_tasks: tasks/mayan_db.yml
