---
- name: Install prereqs for mayan-edms
  apt: >
    pkg={{ item }}
    state=installed
    force=yes
  with_items:
    - libjpeg-dev
    - libmagic1
    - libpng-dev
    - libreoffice
    - libtiff-dev
    - ghostscript
    - gpgv
    - python-dev
    - python-virtualenv
    - tesseract-ocr
    - poppler-utils
