---
- name: install nginx config
  template:
    src: 'etc/nginx/sites-available/app.conf.j2'
    dest: '/etc/nginx/sites-available/mayan.conf'

- name: enable nginx config
  file:
    src: '/etc/nginx/sites-available/mayan.conf'
    dest: '/etc/nginx/sites-enabled/mayan.conf'
    state: 'link'
    force: 'yes'
  notify: restart nginx
